---
# Source: sysdig-deploy/charts/agent/templates/clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sysdig-agent
  labels:
    helm.sh/chart: agent-1.5.58
    app.kubernetes.io/name: agent
    app.kubernetes.io/instance: sysdig-agent
    app.kubernetes.io/version: "12.10.1"
    app.kubernetes.io/managed-by: Helm
    app: "sysdig-agent"
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - replicationcontrollers
      - services
      - endpoints
      - events
      - limitranges
      - namespaces
      - nodes
      - nodes/metrics
      - nodes/proxy
      - resourcequotas
      - persistentvolumes
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - networkpolicies
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - daemonsets
      - deployments
      - replicasets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
    - coordination.k8s.io
    resources:
    - leases
    verbs:
    - get
    - list
    - create
    - update
    - watch
  - nonResourceURLs:
    - /metrics
    verbs:
    - get
  - apiGroups:
    - storage.k8s.io
    resources:
    - storageclasses
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - certificates.k8s.io
    resources:
    - certificatesigningrequests
    verbs:
    - get
    - list
    - watch
