---
# Source: sysdig-deploy/charts/agent/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sysdig-agent
  namespace: sysdig-agent
  labels:
    helm.sh/chart: agent-1.5.58
    app.kubernetes.io/name: agent
    app.kubernetes.io/instance: sysdig-agent
    app.kubernetes.io/version: "12.10.1"
    app.kubernetes.io/managed-by: Helm
    app: "sysdig-agent"
    
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: agent
      app.kubernetes.io/instance: sysdig-agent
  template:
    metadata:
      name: sysdig-agent
      labels:
        helm.sh/chart: agent-1.5.58
        app.kubernetes.io/name: agent
        app.kubernetes.io/instance: sysdig-agent
        app.kubernetes.io/version: "12.10.1"
        app.kubernetes.io/managed-by: Helm
        app: "sysdig-agent"
        
    spec:
      serviceAccountName: sysdig-agent
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
        - effect: NoSchedule
          key: node-role.kubernetes.io/controlplane
          operator: Equal
          value: "true"
        - effect: NoExecute
          key: node-role.kubernetes.io/etcd
          operator: Equal
          value: "true"
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      hostPID: true
      terminationGracePeriodSeconds: 5
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                  - amd64
                  - arm64
                  - s390x
              - key: kubernetes.io/os
                operator: In
                values:
                  - linux
      initContainers:
        - name: sysdig-agent-kmodule
          image: quay.io/sysdig/agent-kmodule:12.10.1
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              drop:
                - ALL
            privileged: true
            runAsNonRoot: false
            runAsUser: 0
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: true
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 1000m
              memory: 348Mi
          env:
          volumeMounts:
            - mountPath: /etc/modprobe.d
              name: modprobe-d
              readOnly: true
            - mountPath: /host/boot
              name: boot-vol
              readOnly: true
            - mountPath: /host/lib/modules
              name: modules-vol
              readOnly: true
            - mountPath: /host/usr
              name: usr-vol
              readOnly: true
            - mountPath: /host/etc
              name: etc-vol
              readOnly: true
      containers:
        - name: sysdig
          image: quay.io/sysdig/agent-slim:12.10.1
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 1000m
              memory: 1024Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          securityContext:
            capabilities:
              drop:
                - ALL
            privileged: true
            runAsNonRoot: false
            runAsUser: 0
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: true
          env:
            - name: K8S_NODE
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          readinessProbe:
            exec:
              command: [ "test", "-e", "/opt/draios/logs/running" ]
            initialDelaySeconds: 90
          volumeMounts:
            - mountPath: /host/etc
              name: etc-vol
              readOnly: true
            - mountPath: /host/dev
              name: dev-vol
              readOnly: false
            - mountPath: /host/proc
              name: proc-vol
              readOnly: true
            - mountPath: /host/run
              name: run-vol
            - mountPath: /host/var/run
              name: varrun-vol
            - mountPath: /dev/shm
              name: dshm
            - mountPath: /opt/draios/etc/kubernetes/config
              name: sysdig-agent-config
            - mountPath: /opt/draios/etc/kubernetes/secrets
              name: sysdig-agent-secrets
            - mountPath: /etc/podinfo
              name: podinfo
      volumes:
        - name: modprobe-d
          hostPath:
            path: /etc/modprobe.d
        - name: dshm
          emptyDir:
            medium: Memory
        - name: etc-vol
          hostPath:
            path: /etc
        - name: dev-vol
          hostPath:
            path: /dev
        - name: proc-vol
          hostPath:
            path: /proc
        - name: boot-vol
          hostPath:
            path: /boot
        - name: modules-vol
          hostPath:
            path: /lib/modules
        - name: usr-vol
          hostPath:
            path: /usr
        - name: run-vol
          hostPath:
            path: /run
        - name: varrun-vol
          hostPath:
            path: /var/run
        - name: sysdig-agent-config
          configMap:
            name: sysdig-agent
            optional: true
        - name: sysdig-agent-secrets
          secret:
            secretName: sysdig-agent
        - name: podinfo
          downwardAPI:
            defaultMode: 420
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
              path: name
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
