---
# Source: sysdig-deploy/charts/agent/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: sysdig-agent
  namespace: sysdig-agent
  labels:
    helm.sh/chart: agent-1.5.58
    app.kubernetes.io/name: agent
    app.kubernetes.io/instance: sysdig-agent
    app.kubernetes.io/version: "12.10.1"
    app.kubernetes.io/managed-by: Helm
    app: "sysdig-agent"
type: Opaque
data:
 access-key : "NTA0MmQ4NTMtMGE2OC00NWVlLTliYjMtMTg5NTdjNGRiZjE4"
